namespace Kampai.Game
{
	public enum FtueLevel
	{
		NOT_STARTED = 0,
		REPAIR_TIKI_BAR = 1,
		PLACE_LEISURE_BUILDING = 2,
		ENABLE_BUFFED_PARTY = 3,
		REPAIR_STORAGE = 4,
		FETCH_COCONUTS = 5,
		HARVEST_COCONUTS = 6,
		REPAIR_ORDER_BOARD = 7,
		FILL_ORDER = 8,
		PUSH_NOTIFICATIONS = 9,
		FTUE_COMPLETED = 999999
	}
}
