namespace Kampai.Game
{
	public enum GameElement
	{
		CONTEXT = 0,
		MINION_MANAGER = 1,
		BUILDING_MANAGER = 2,
		GROUND_PLANE = 3,
		BUILDING_FOOTPRINT = 4,
		FLOWER_PARENT = 5,
		FOR_SALE_SIGN_PARENT = 6,
		TIKIBAR_VIEW_END_LOCATION = 7,
		NAMED_CHARACTER_MANAGER = 8,
		VILLAIN_MANAGER = 9,
		LAND_EXPANSION_PARENT = 10,
		RELOCATION_POINTS = 11,
		FADE_AUDIO_EMITTER = 12,
		PARTY_OBJECT = 13,
		SPECIAL_EVENT_PARENT = 14,
		VILLAIN_LAIR_PARENT = 15
	}
}
