namespace Kampai.Game
{
	public enum TransactionTarget
	{
		NO_VISUAL = 0,
		HARVEST = 1,
		REWARD_BUILDING = 2,
		BLACKMARKETBOARD = 3,
		MARKETPLACE = 4,
		INGREDIENT = 5,
		STORAGEBUILDING = 6,
		CURRENCY = 7,
		EXCHANGE = 8,
		QUEST_REWARD = 9,
		TASK_COMPLETE = 10,
		TASK_COMPLETE_INGREDIENT = 11,
		CLEAR_DEBRIS = 12,
		REPAIR_BRIDGE = 13,
		LAND_EXPANSION = 14,
		AUTOMATIC = 15
	}
}
