public class NimbleBridge_TrackingConstants
{
	public const string STANDARD_EVENT_PREFIX = "NIMBLESTANDARD::";

	public const string EVENT_APPSTART_NORMAL = "NIMBLESTANDARD::APPSTART_NORMAL";

	public const string EVENT_APPSTART_AFTERINSTALL = "NIMBLESTANDARD::APPSTART_AFTERINSTALL";

	public const string EVENT_APPSTART_AFTERUPGRADE = "NIMBLESTANDARD::APPSTART_AFTERUPGRADE";

	public const string EVENT_APPSTART_FROMPUSH = "NIMBLESTANDARD::APPSTART_FROMPUSH";

	public const string EVENT_APPSTART_FROMURL = "NIMBLESTANDARD::APPSTART_FROMURL";

	public const string EVENT_SESSION_START = "NIMBLESTANDARD::SESSION_START";

	public const string EVENT_APPRESUME_FROMURL = "NIMBLESTANDARD::APPRESUME_FROMURL";

	public const string EVENT_APPRESUME_NORMAL = "NIMBLESTANDARD::APPRESUME_NORMAL";

	public const string EVENT_APPRESUME_FROMPUSH = "NIMBLESTANDARD::APPRESUME_FROMPUSH";

	public const string EVENT_APPRESUME_FROMEBISU = "NIMBLESTANDARD::APPRESUME_FROMEBISU";

	public const string EVENT_SESSION_TIME = "NIMBLESTANDARD::SESSION_TIME";

	public const string EVENT_SESSION_END = "NIMBLESTANDARD::SESSION_END";

	public const string EVENT_USER_REGISTERED = "NIMBLESTANDARD::USER_REGISTERED";

	public const string EVENT_MTX_ITEM_BEGIN_PURCHASE = "NIMBLESTANDARD::MTX_ITEM_BEGIN_PURCHASE";

	public const string EVENT_MTX_ITEM_PURCHASED = "NIMBLESTANDARD::MTX_ITEM_PURCHASED";

	public const string EVENT_MTX_FREEITEM_DOWNLOADED = "NIMBLESTANDARD::MTX_FREEITEM_DOWNLOADED";

	public const string EVENT_MTX_PURCHASE_DEFERRED = "NIMBLESTANDARD::MTX_PURCHASE_DEFERRED";

	public const string EVENT_MTX_DEF_PURCHASE_APPROVED = "NIMBLESTANDARD::MTX_DEF_PURCHASE_APPROVED";

	public const string EVENT_MTX_DEF_PURCHASE_EXPIRED = "NIMBLESTANDARD::MTX_DEF_PURCHASE_EXPIRED";

	public const string EVENT_MTX_DEF_PURCHASE_DECLINED = "NIMBLESTANDARD::MTX_DEF_PURCHASE_DECLINED";

	public const string EVENT_MTX_RECEIPT_VALIDATION = "NIMBLESTANDARD::MTX_RECEIPT_VALIDATION";

	public const string EVENT_USER_TRACKING_OPTOUT = "NIMBLESTANDARD::USER_TRACKING_OPTOUT";

	public const string EVENT_TUTORIAL_COMPLETE = "NIMBLESTANDARD::TUTORIAL_COMPLETE";

	public const string EVENT_LEVEL_UP = "NIMBLESTANDARD::LEVEL_UP";

	public const string EVENT_PN_DISPLAY_OPT_IN = "NIMBLESTANDARD::PN_DISPLAY_OPT_IN";

	public const string EVENT_PN_USER_OPT_IN = "NIMBLESTANDARD::PN_USER_OPT_IN";

	public const string EVENT_PN_SHOWN_TO_USER = "NIMBLESTANDARD::PN_SHOWN_TO_USER";

	public const string EVENT_PN_USER_CLICKED_OK = "NIMBLESTANDARD::PN_USER_CLICKED_OK";

	public const string EVENT_IDENTITY_MIGRATION = "NIMBLESTANDARD::IDENTITY_MIGRATION";

	public const string EVENT_IDENTITY_LOGIN = "NIMBLESTANDARD::IDENTITY_LOGIN";

	public const string EVENT_IDENTITY_LOGOUT = "NIMBLESTANDARD::IDENTITY_LOGOUT";

	public const string EVENT_IDENTITY_MIGRATION_STARTED = "NIMBLESTANDARD::IDENTITY_MIGRATION_STARTED";

	public const string KEY_USERNAME = "NIMBLESTANDARD::KEY_USERNAME";

	public const string KEY_USER_LEVEL = "NIMBLESTANDARD::KEY_USER_LEVEL";

	public const string KEY_DURATION = "NIMBLESTANDARD::KEY_DURATION";

	public const string KEY_GAMEPLAY_DURATION = "NIMBLESTANDARD::KEY_GAMEPLAY_DURATION";

	public const string KEY_MTX_PRICE = "NIMBLESTANDARD::KEY_MTX_PRICE";

	public const string KEY_MTX_CURRENCY = "NIMBLESTANDARD::KEY_MTX_CURRENCY";

	public const string KEY_MTX_SELLID = "NIMBLESTANDARD::KEY_MTX_SELLID";

	public const string KEY_MTX_APPLE_TRANSACTION_ID = "NIMBLESTANDARD::KEY_MTX_APPLE_TRANSACTION_ID";

	public const string KEY_MTX_EA_TRANSACTION_ID = "NIMBLESTANDARD::KEY_MTX_EA_TRANSACTION_ID";

	public const string KEY_PN_MESSAGEID = "NIMBLESTANDARD::KEY_PN_MESSAGE_ID";

	public const string KEY_MIGRATION_GAME_TRIGGERED = "NIMBLESTANDARD::KEY_MIGRATION_GAME_TRIGGERED";

	public const string KEY_IDENTITY_PIDMAP_LOGIN = "NIMBLESTANDARD::KEY_IDENTITY_PIDMAP_LOGIN";

	public const string KEY_IDENTITY_PIDMAP_LOGOUT = "NIMBLESTANDARD::KEY_IDENTITY_PIDMAP_LOGOUT";

	public const string KEY_IDENTITY_MAP_SOURCE = "NIMBLESTANDARD::KEY_IDENTITY_SOURCE";

	public const string KEY_IDENTITY_MAP_TARGET = "NIMBLESTANDARD::KEY_IDENTITY_TARGET";

	public const string NIMBLE_TRACKING_ATTRIBUTE_PROGRESSION_LEVEL = "NIMBLESTANDARD::ATTRIBUTE_PROGRESSION_LEVEL";
}
